### ISSUE TITLE
Categories: setting them in code, extending them

### ISSUE THREAD

**Issue by mildlydiverting** [culturehack/data-tool#23]
Currently, our categories are (i think) defined in site.rb lines 6-14

```
  CATEGORIES = [
    'Art', 
    'Literature',
    'Music', 
    'Performance', 
    'Fashion', 
    'Media', 
    'History'
  ]
```

They're also then listed out in _prose.yml line 18 on

```
 - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          options:
            - name: "Art"
              value: "Art"
```

QUESTIONS:

To add a new category, or rename an existing category, is it just a case of editing them in those two places?
Can Categories take spaces? If so, do they need to be surrounded by quotes in site.rb and any of the source.md files?
